language: node_js
node_js:
- node
notifications:
  slack:
    secure: Ut635OBE5kLYKjq35PSttT3Ux9nv+hW79r84V9D9QgqoAH1oBoMrMVdt7j07JeGu8OMHaGx7EH3CFlGLTdl9sLf3JWa5aVHKh23jQ+4O6ia+0VOKByAf/aH0css+YizYMYit+BlQ9y9LNldEMtk/ek2M5Ugkoah58qaVcjt1iNtUjHqZqOIIV5+gV+xJ13rn6dri9toWu8k8f1SgeyXOuiyOqX6Ot63Dxem/jkqyU9D5YsTkNW2ED53UYhWx9ONpJjUHlP53FdUIfPeELG1ctV1iuqftW3F0vm3LHmoptgPkC1ffVfD5zzA6lGpRD359rkI5t7MjseD73vXlQUvg475erIl8zYBNeIFP/HLH34Z73BmIrtvh1H+ZpOwpYQ0LSlZh9WaWDJ5KcjLpTcW/39wkceVNKGsqjbKy1Hgccp6KYNCQLvKRh+bNnP4yzLMJBXHrVjwgoYrBYKcoh4PhCW7h76UEck2WBA1V/Kc0bgtdLO7krhTZhFGRsSTKxohLGlqZ4n46TPOtFy5AZBakiZH8yBJLdLS8oPPK71YbywQOLggnyszNXyhKAtzUJpmMDsEFeDU47xTr5ifhNHZhN89vPwEwj3T+M3QfL5N6o9gtYcwYz+Dr161NFO573E1iFUS5D1O41MfK59gfyhrFUHfXC7+FoMPL2VrCC2AtgQ8=
